name: Update Instagram Insights   # <- nome visibile in Actions

on:
  workflow_dispatch:              # <- abilita il pulsante "Run workflow"
  schedule:
    - cron: '0 6 * * *'          # opzionale: ogni giorno alle 06:00 UTC

permissions:
  contents: write                 # necessario per fare commit dal job

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python insight_folignotouch.py

      - name: Commit & push artifacts
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add static/insight_folignotouch_30d.csv static/reach_30d.png
          # Se non ci sono modifiche, esci senza errore
          git diff --cached --quiet && echo "Nessuna modifica da committare" && exit 0
          git commit -m "Update insights and chart [skip ci]"
          git push
