name: Update Instagram Insights

on:
  workflow_dispatch:   # avvio manuale
  schedule:
    - cron: "0 6 * * *" # ogni giorno alle 6:00 UTC

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        with:
        fetch-depth: 0
    
    - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python insight_folignotouch.py

      - name: Debug generated files
        run: ls -lh static

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add static/insight_folignotouch_30d.csv static/reach_30d.png
          git commit -m "🔄 Update insights and chart [skip ci]" || echo "No changes to commit"
          git push
